spring:
  data:
    mongodb:
      database: onego
      uri: mongodb://onego:test123@onegodev.ddns.net:2727/test?authSource=admin&readPreference=primary&directConnection=true&ssl=false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
